permalink: /blog/:categories/:year/:month/:day/:title/

analytics:
  code: UA-43992716-3
  domain: community-management.nub.is

asset_bundler:
  base_path: /assets/bundles/
  compress:
    js: yui
    css: yui

paginate: 6
paginate_path: "/blog/artikelen/page:num"
